services:

  nexus-backend:
    build: ./backend
    env_file: ./backend/.env
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=nexus-backend.mec.ac.in
      - VIRTUAL_PORT=8000

  nexus-frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
    depends_on:
      - nexus-backend
    environment:
      - VIRTUAL_HOST=nexus.mec.ac.in
    restart: unless-stopped

networks:
  default:
    name: mec
    external: true
