"""PDF generation for an approved NEXUS event permission letter."""

from io import BytesIO

from reportlab.lib.colors import HexColor, white
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfbase.pdfmetrics import stringWidth
from reportlab.pdfgen import canvas


PAGE_WIDTH, PAGE_HEIGHT = A4
RED = HexColor("#D92525")
INK = HexColor("#151515")
MUTED = HexColor("#B8B8B8")
LINE = HexColor("#D9D9D9")


def _wrap_text(text: str, font: str, size: int, max_width: float) -> list[str]:
    words = (text or "").split()
    lines, line = [], ""
    for word in words:
        candidate = f"{line} {word}".strip()
        if line and stringWidth(candidate, font, size) > max_width:
            lines.append(line)
            line = word
        else:
            line = candidate
    if line:
        lines.append(line)
    return lines or [""]


def build_permission_letter(event, approver_name: str, approver_role: str) -> bytes:
    """Return a one-page, printable permission letter for an approved event."""
    stream = BytesIO()
    pdf = canvas.Canvas(stream, pagesize=A4)
    margin = 22 * mm
    content_width = PAGE_WIDTH - (2 * margin)

    pdf.setFillColor(INK)
    pdf.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, fill=1, stroke=0)
    pdf.setFillColor(white)
    pdf.setFont("Helvetica-Bold", 21)
    pdf.drawString(margin, PAGE_HEIGHT - 32 * mm, "NEXUS.")
    pdf.setFont("Helvetica", 8)
    pdf.setFillColor(HexColor("#C9C9C9"))
    pdf.drawRightString(PAGE_WIDTH - margin, PAGE_HEIGHT - 29 * mm, "COLLEGE EVENT MANAGEMENT PLATFORM")
    pdf.setStrokeColor(RED)
    pdf.setLineWidth(2)
    pdf.line(margin, PAGE_HEIGHT - 37 * mm, PAGE_WIDTH - margin, PAGE_HEIGHT - 37 * mm)

    y = PAGE_HEIGHT - 57 * mm
    pdf.setFillColor(RED)
    pdf.setFont("Helvetica-Bold", 9)
    pdf.drawString(margin, y, "OFFICIAL PERMISSION LETTER")
    y -= 14 * mm

    pdf.setFillColor(white)
    pdf.setFont("Helvetica-Bold", 24)
    for line in _wrap_text(event.title, "Helvetica-Bold", 24, content_width):
        pdf.drawString(margin, y, line)
        y -= 10 * mm

    y -= 4 * mm
    pdf.setFillColor(HexColor("#D0D0D0"))
    pdf.setFont("Helvetica", 11)
    date_label = f"{event.date} | {event.start_time} - {event.end_time}"
    pdf.drawString(margin, y, date_label)
    y -= 7 * mm
    pdf.drawString(margin, y, f"Venue: {event.venue}")
    y -= 15 * mm

    pdf.setStrokeColor(LINE)
    pdf.setLineWidth(0.5)
    pdf.line(margin, y, PAGE_WIDTH - margin, y)
    y -= 13 * mm

    pdf.setFillColor(white)
    pdf.setFont("Helvetica", 11)
    body = (
        f"This is to certify that the event organized by {event.organizer} has been "
        "reviewed and granted permission to proceed as stated above. The organizing "
        "team must follow all applicable college policies, venue requirements, and "
        "safety instructions."
    )
    for line in _wrap_text(body, "Helvetica", 11, content_width):
        pdf.drawString(margin, y, line)
        y -= 6.5 * mm

    y -= 17 * mm
    pdf.setFillColor(RED)
    pdf.setFont("Helvetica-Bold", 9)
    pdf.drawString(margin, y, "APPROVED BY")
    y -= 7 * mm
    pdf.setFillColor(white)
    pdf.setFont("Helvetica-Bold", 13)
    pdf.drawString(margin, y, approver_name or "NEXUS Administration")
    y -= 6 * mm
    pdf.setFillColor(HexColor("#C9C9C9"))
    pdf.setFont("Helvetica", 10)
    pdf.drawString(margin, y, (approver_role or "Approver").title())

    pdf.setFillColor(MUTED)
    pdf.setFont("Helvetica", 8)
    pdf.drawRightString(PAGE_WIDTH - margin, 18 * mm, "Generated by NEXUS - valid for this approved event only")
    pdf.showPage()
    pdf.save()
    return stream.getvalue()
